micronaut:
  application:
    name: aws-lambda-graal-kotlin
jackson:
  bean-introspection-module: true
  date-format: yyyy-MM-dd HH:mm:ss
#  indentOutput: true TODO PR to update docs?
#  writeDatesAsTimestamps: true TODO PR to update docs?

rss:
  baseurl: https://www.blu-ray.com/rss
  path: /newreleasesfeed.xml